### PR TITLE
UI Improvements and Fixes

### LINKED ISSUE #69: UI Improvements and Branding

### PR DESCRIPTION
**Pull request by NandiniMeh**
**View the walkthrough to see the UI changes made!**
- Felt like blue + purple matched our vibe so created some custom components (blue buttons and purple info cards) - Drop in some other color combo suggestions if you are feeling something else!
- Made the pages scrollable (full page scroll) to prevent any components being cut off
- Also fixed a bug on the view receipts page (it was a filter issue)

https://github.com/user-attachments/assets/a05b142f-969d-40db-a8ed-7a37c849a0a3

### CODE REVIEW

File: app/src/main/java/edu/card/clarity/presentation/myReceiptsScreen/MyReceiptsScreenViewModel.kt
Comment (LideLinusZhang) [inline app/src/main/java/edu/card/clarity/presentation/myReceiptsScreen/MyReceiptsScreenViewModel.kt:1]: Changes in this file are mostly unwarranted.

File: app/src/main/java/edu/card/clarity/presentation/recordReceiptScreen/RecordReceiptScreen.kt [hunk 1]
```diff
@@ -59,113 +65,130 @@ fun RecordReceiptScreen(
     val cameraPermissionState = rememberPermissionState(permission = Manifest.permission.CAMERA)
 
     CardClarityTheme {
-        Column(
+        LazyColumn(
```
Comment (LideLinusZhang) [inline app/src/main/java/edu/card/clarity/presentation/recordReceiptScreen/RecordReceiptScreen.kt]: `LazyColumn` is for presenting a huge list of data so that only viewable data are fetched and rendered. Here we only have a fixed number of widgets, so using `Column` is fine.

**Review by LideLinusZhang — CHANGES_REQUESTED** [review]

**Review by LideLinusZhang — APPROVED** [review]
